spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kcr?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: thfla0901@
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: API-KEY  # 추가된 프로파일 설정

logging.level:
  org:
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

# 여기부터 새로 추가하는 설정
openai:
  api:
    token: "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"
  url:
    endpoint: https://api.openai.com/v1/completions
  model: text-davinci-003

